package com.xceder.ctp.market;
import org.bridj.Pointer;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.ann.Ptr;
import org.bridj.ann.Virtual;
import org.bridj.cpp.CPPObject;
/**
 * <i>native declaration : ThostFtdcMdApi.h:66</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Thostmduserapi") 
public class CThostFtdcMdApi extends CPPObject {
	/**
	 * modify for udp marketdata<br>
	 * Original signature : <code>CThostFtdcMdApi* CreateFtdcMdApi(const char*, const bool, const bool)</code><br>
	 * <i>native declaration : ThostFtdcMdApi.h:73</i>
	 */
	public static Pointer<CThostFtdcMdApi > CreateFtdcMdApi(Pointer<Byte > pszFlowPath, boolean bIsUsingUdp, boolean bIsMulticast) {
		return Pointer.pointerToAddress(CreateFtdcMdApi(Pointer.getPeer(pszFlowPath), bIsUsingUdp, bIsMulticast), CThostFtdcMdApi.class);
	}
	@Ptr 
	protected native static long CreateFtdcMdApi(@Ptr long pszFlowPath, boolean bIsUsingUdp, boolean bIsMulticast);
	/**
	 * @retrun \ufffd\ufffd\u0221\ufffd\ufffd\ufffd\u0130\u6c7e\ufffd\ufffd<br>
	 * Original signature : <code>char* GetApiVersion()</code><br>
	 * <i>native declaration : ThostFtdcMdApi.h:77</i>
	 */
	public static Pointer<Byte > GetApiVersion() {
		return Pointer.pointerToAddress(GetApiVersion$2(), Byte.class);
	}
	@Ptr 
	@Name("GetApiVersion") 
	protected native static long GetApiVersion$2();
	/**
	 * @remark \ufffd\ufffd\ufffd\ufffd\u02b9\ufffd\u00f1\ufffd\ufffd\u04ff\u06b6\ufffd\ufffd\ufffd\u02b1,\ufffd\ufffd\ufffd\u00f8\u00fa\ufffd\ufffd\ufffd\u027e\ufffd\ufffd\ufffd\u04ff\u06b6\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>void Release()</code><br>
	 * <i>native declaration : ThostFtdcMdApi.h:81</i>
	 */
	@Virtual(0) 
	native public void Release();
	/**
	 * @remark \ufffd\ufffd\u02bc\ufffd\ufffd\ufffd\ufffd\ufffd\u043b\ufffd\ufffd\ufffd,\u05bb\ufffd\u0435\ufffd\ufffd\u00fa\ufffd,\ufffd\u04ff\u06b2\u017f\ufffd\u02bc\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>void Init()</code><br>
	 * <i>native declaration : ThostFtdcMdApi.h:85</i>
	 */
	@Virtual(1) 
	native public void Init();
	/**
	 * @return \ufffd\u07f3\ufffd\ufffd\u02f3\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int Join()</code><br>
	 * <i>native declaration : ThostFtdcMdApi.h:89</i>
	 */
	@Virtual(2) 
	native public int Join();
	/**
	 * @remark \u05bb\ufffd\u0435\ufffd\u00bc\ufffd\u0279\ufffd\ufffd\ufffd,\ufffd\ufffd\ufffd\u0735\u00f5\ufffd\ufffd\ufffd\u0237\ufffd\u013d\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>char* GetTradingDay()</code><br>
	 * <i>native declaration : ThostFtdcMdApi.h:94</i>
	 */
	@Virtual(3) 
	public Pointer<Byte > GetTradingDay() {
		return Pointer.pointerToAddress(GetTradingDay$2(), Byte.class);
	}
	@Ptr 
	@Name("GetTradingDay") 
	@Virtual(3) 
	protected native long GetTradingDay$2();
	/**
	 * @remark \ufffd\ufffdtcp\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u042d\ufffd\u98ec\ufffd\ufffd127.0.0.1\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u05b7\ufffd\ufffd\ufffd\ufffd17001\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u02ff\u06ba\u0161\ufffd<br>
	 * Original signature : <code>void RegisterFront(char*)</code><br>
	 * <i>native declaration : ThostFtdcMdApi.h:100</i>
	 */
	@Virtual(4) 
	public void RegisterFront(Pointer<Byte > pszFrontAddress) {
		RegisterFront(Pointer.getPeer(pszFrontAddress));
	}
	@Virtual(4) 
	protected native void RegisterFront(@Ptr long pszFrontAddress);
	/**
	 * @remark RegisterNameServer\ufffd\ufffd\ufffd\ufffd\ufffd\ufffdRegisterFront<br>
	 * Original signature : <code>void RegisterNameServer(char*)</code><br>
	 * <i>native declaration : ThostFtdcMdApi.h:107</i>
	 */
	@Virtual(5) 
	public void RegisterNameServer(Pointer<Byte > pszNsAddress) {
		RegisterNameServer(Pointer.getPeer(pszNsAddress));
	}
	@Virtual(5) 
	protected native void RegisterNameServer(@Ptr long pszNsAddress);
	/**
	 * @param pFensUserInfo\ufffd\ufffd\ufffd\u00fb\ufffd\ufffd\ufffd\u03e2\ufffd\ufffd<br>
	 * Original signature : <code>void RegisterFensUserInfo(CThostFtdcFensUserInfoField*)</code><br>
	 * <i>native declaration : ThostFtdcMdApi.h:111</i>
	 */
	@Virtual(6) 
	public void RegisterFensUserInfo(Pointer<CThostFtdcFensUserInfoField > pFensUserInfo) {
		RegisterFensUserInfo(Pointer.getPeer(pFensUserInfo));
	}
	@Virtual(6) 
	protected native void RegisterFensUserInfo(@Ptr long pFensUserInfo);
	/**
	 * @param pSpi \ufffd\ufffd\ufffd\ufffd\ufffd\u053b\u0635\ufffd\ufffd\u04ff\ufffd\ufffd\ufffd\ufffd\u02b5\ufffd\ufffd<br>
	 * Original signature : <code>void RegisterSpi(CThostFtdcMdSpi*)</code><br>
	 * <i>native declaration : ThostFtdcMdApi.h:115</i>
	 */
	@Virtual(7) 
	public void RegisterSpi(Pointer<CThostFtdcMdSpi > pSpi) {
		RegisterSpi(Pointer.getPeer(pSpi));
	}
	@Virtual(7) 
	protected native void RegisterSpi(@Ptr long pSpi);
	/**
	 * @remark<br>
	 * Original signature : <code>int SubscribeMarketData(char*[], int)</code><br>
	 * <i>native declaration : ThostFtdcMdApi.h:121</i>
	 */
	@Virtual(8) 
	public int SubscribeMarketData(Pointer<Pointer<Byte > > ppInstrumentID, int nCount) {
		return SubscribeMarketData(Pointer.getPeer(ppInstrumentID), nCount);
	}
	@Virtual(8) 
	protected native int SubscribeMarketData(@Ptr long ppInstrumentID, int nCount);
	/**
	 * @remark<br>
	 * Original signature : <code>int UnSubscribeMarketData(char*[], int)</code><br>
	 * <i>native declaration : ThostFtdcMdApi.h:127</i>
	 */
	@Virtual(9) 
	public int UnSubscribeMarketData(Pointer<Pointer<Byte > > ppInstrumentID, int nCount) {
		return UnSubscribeMarketData(Pointer.getPeer(ppInstrumentID), nCount);
	}
	@Virtual(9) 
	protected native int UnSubscribeMarketData(@Ptr long ppInstrumentID, int nCount);
	/**
	 * @remark<br>
	 * Original signature : <code>int SubscribeForQuoteRsp(char*[], int)</code><br>
	 * <i>native declaration : ThostFtdcMdApi.h:133</i>
	 */
	@Virtual(10) 
	public int SubscribeForQuoteRsp(Pointer<Pointer<Byte > > ppInstrumentID, int nCount) {
		return SubscribeForQuoteRsp(Pointer.getPeer(ppInstrumentID), nCount);
	}
	@Virtual(10) 
	protected native int SubscribeForQuoteRsp(@Ptr long ppInstrumentID, int nCount);
	/**
	 * @remark<br>
	 * Original signature : <code>int UnSubscribeForQuoteRsp(char*[], int)</code><br>
	 * <i>native declaration : ThostFtdcMdApi.h:139</i>
	 */
	@Virtual(11) 
	public int UnSubscribeForQuoteRsp(Pointer<Pointer<Byte > > ppInstrumentID, int nCount) {
		return UnSubscribeForQuoteRsp(Pointer.getPeer(ppInstrumentID), nCount);
	}
	@Virtual(11) 
	protected native int UnSubscribeForQuoteRsp(@Ptr long ppInstrumentID, int nCount);
	/**
	 * \ufffd\u00fb\ufffd\ufffd\ufffd\u00bc\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqUserLogin(CThostFtdcReqUserLoginField*, int)</code><br>
	 * <i>native declaration : ThostFtdcMdApi.h:142</i>
	 */
	@Virtual(12) 
	public int ReqUserLogin(Pointer<CThostFtdcReqUserLoginField > pReqUserLoginField, int nRequestID) {
		return ReqUserLogin(Pointer.getPeer(pReqUserLoginField), nRequestID);
	}
	@Virtual(12) 
	protected native int ReqUserLogin(@Ptr long pReqUserLoginField, int nRequestID);
	/**
	 * \ufffd\u01f3\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqUserLogout(CThostFtdcUserLogoutField*, int)</code><br>
	 * <i>native declaration : ThostFtdcMdApi.h:146</i>
	 */
	@Virtual(13) 
	public int ReqUserLogout(Pointer<CThostFtdcUserLogoutField > pUserLogout, int nRequestID) {
		return ReqUserLogout(Pointer.getPeer(pUserLogout), nRequestID);
	}
	@Virtual(13) 
	protected native int ReqUserLogout(@Ptr long pUserLogout, int nRequestID);
	public CThostFtdcMdApi() {
		super();
	}
	public CThostFtdcMdApi(Pointer pointer) {
		super(pointer);
	}
}
