package com.xceder.ctp.trade;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u02bd\ufffd\u0423\ufffd\ufffd\u0123\u02bd<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:4991</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Thosttraderapi") 
public class CThostFtdcSecAgentCheckModeField extends StructObject {
	/**
	 * \u0376\ufffd\ufffd\ufffd\u07f4\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	@Array({13}) 
	@Field(0) 
	public Pointer<Byte > InvestorID() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \ufffd\ufffd\ufffd\u0379\ufffd\u02fe\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({11}) 
	@Field(1) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcCurrencyIDType
	 */
	@Array({4}) 
	@Field(2) 
	public Pointer<Byte > CurrencyID() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u043d\ufffd\ufffd\ufffd\ufffd\ufffd\u02bd\ufffd\ufffd\u02ba\ufffd<br>
	 * C type : TThostFtdcAccountIDType
	 */
	@Array({13}) 
	@Field(3) 
	public Pointer<Byte > BrokerSecAgentID() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * \ufffd\u01f7\ufffd\ufffd\ufffd\u04aa\u0423\ufffd\ufffd\ufffd\u053c\ufffd\ufffd\ufffd\ufffd\u02bd\ufffd\ufffd\u02fb\ufffd<br>
	 * C type : TThostFtdcBoolType
	 */
	@Field(4) 
	public int CheckSelfAccount() {
		return this.io.getIntField(this, 4);
	}
	/**
	 * \ufffd\u01f7\ufffd\ufffd\ufffd\u04aa\u0423\ufffd\ufffd\ufffd\u053c\ufffd\ufffd\ufffd\ufffd\u02bd\ufffd\ufffd\u02fb\ufffd<br>
	 * C type : TThostFtdcBoolType
	 */
	@Field(4) 
	public CThostFtdcSecAgentCheckModeField CheckSelfAccount(int CheckSelfAccount) {
		this.io.setIntField(this, 4, CheckSelfAccount);
		return this;
	}
	public CThostFtdcSecAgentCheckModeField() {
		super();
	}
	public CThostFtdcSecAgentCheckModeField(Pointer pointer) {
		super(pointer);
	}
}
